import os

SLACK_WEBHOOK = os.getenv('CHEF_SLACK_WEBHOOK')
SLACK_CHANNEL = os.getenv('CHEF_SLACK_CHANNEL')
ZOMATO_API_KEY = os.getenv('CHEF_ZOMATO_API_KEY')
TIME = os.getenv('CHEF_NOTIFY_AT', '11:00')

